spring.application.name=cloud-disk
spring.datasource.url=jdbc:mysql://localhost:3306/cloud_disk?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.clouddisk.entity

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

file.upload-dir=D:/cloud-disk-files/
mybatis.configuration.map-underscore-to-camel-case=true

spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=3474468103@qq.com
spring.mail.password=ugzhhbkvcbuacjga
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.auth.mechanisms=LOGIN
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.qq.com
spring.mail.default-encoding=UTF-8
spring.mail.protocol=smtp